name: cart_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  products_repository : 
    path: ../products_repository 
  api_repository:
    path: ../api_repository
  user_repository:
    path: ../user_repository
  intl: ^0.20.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
